apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    {{ toYaml .Values.labels | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      appName: {{ .Values.name }}
  template:
    metadata:
      labels:
        {{ toYaml .Values.labels | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.name }}-{{ .Values.env }}
        image: 633788536644.dkr.ecr.us-east-1.amazonaws.com/roboshop-{{ .Values.name }}:{{ .Values.appVersion }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.port }}
        envFrom:
        - secretRef:
            name: {{ .Values.name }}
        resources:
          {{ toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.port }}
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.port }}
          initialDelaySeconds: 30
          periodSeconds: 30
          failureThreshold: 3


