apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.name }}
spec:
  refreshInterval: "5s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ .Values.name }}
  dataFrom:
  - extract:
      key: {{ .Values.name }}
