apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.name }}
  namespace: roboshop
  labels:
    appName: {{ .Values.name }}
spec:
  containers:
    - name: {{ .Values.name }}
      image: public.ecr.aws/w8x4g9h7/roboshop-v3/{{ .Values.name }}
      env:
        {{ include "toYaml" .Values.env | indent 8 }}


