apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.name }}
  labels:
    appName: {{ .Values.name }}
spec:
  containers:
    - name: {{ .Values.name }}
      image: public.ecr.aws/w8x4g9h7/roboshop-v3/{{ .Values.name }}
      envFrom:
      - secretRef:
          name: {{ .Values.name }}


