{{- if .Values.schema.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}-schema
  labels:
    appName: {{ .Values.name }}
spec:
  template:
    spec:
      containers:
      - name: {{ .Values.name }}
        image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
        env:
          {{- toYaml .Values.schema.env | nindent 10 }}
  backoffLimit: 0
{{- end -}}

