{{- if .Values.schema.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}-schema
  labels:
    appName: {{ .Values.name }}
spec:
  template:
    spec:
      containers:
      - name: {{ .Values.name }}
        image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
        env:
          - name: DB_TYPE
            value: mongo
          - name: APP_GIT_URL
            value: "https://github.com/roboshop-devops-project-v3/catalogue"
          - name: DB_HOST
            value: mongo.dev.rdevopsb80.online
          - name: SCHEMA_FILE
            value: db/master-data.js
      restartPolicy: Never
  backoffLimit: 0
{{- end -}}
