{{- if .Values.schema.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}-schema
  labels:
    appName: {{ .Values.name }}
spec:
  template:
    spec:
      containers:
        {{- range $k, $v := .Values.schema.containers }}
        - name: {{ $k }}
          image: 633788536644.dkr.ecr.us-east-1.amazonaws.com/schema-load:latest
          imagePullPolicy: Always
          env:
            {{- toYaml $.Values.schema.env | nindent 12 }}
        {{- end }}
      restartPolicy: Never
  backoffLimit: 0
{{- end -}}

