{{- if .Values.schema.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}-schema
  labels:
    appName: {{ .Values.name }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: {{ .Values.name }}-schema
          image: 633788536644.dkr.ecr.us-east-1.amazonaws.com/schema-load:{{ .Values.name }}
          imagePullPolicy: Always
          securityContext:
            readOnlyRootFilesystem: true
          envFrom:
          - secretRef:
              name: {{ .Values.name }}
      restartPolicy: Never
  backoffLimit: 0
{{- end -}}

