{{- if .Values.schema.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}-schema
  labels:
    appName: {{ .Values.name }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: schema-load
          image: 633788536644.dkr.ecr.us-east-1.amazonaws.com/schema-load:latest
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: {{ .Values.name }}
      restartPolicy: Never
  backoffLimit: 0
{{- end -}}

