{{- if .Values.schema.enabled -}}
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ .Values.name }}
spec:
  mtls:
    mode: STRICT  # Enforce mTLS for all services in this namespace
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
 name: {{ .Values.name }}-allow
spec:
  selector:
    matchLabels:
      appName: {{ .Values.name }}
  action: ALLOW
  rules:
  - from:
    - source:
        principals: {{ .Values.istio.principals }}
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: {{ .Values.name }}-deny
spec:
  selector:
    matchLabels:
      appName: {{ .Values.name }}
  action: DENY
  rules:
  - from:
    - source:
        notPrincipals: {{ .Values.istio.principals }}
{{- end -}}
